FROM openjdk:11
EXPOSE 9098
MAINTAINER Arya Vardhan aryav709@gmail.com
COPY ./target/plasmaDonationManagement-0.0.1-SNAPSHOT.jar ./
WORKDIR ./
CMD ["java", "-jar", "plasmaDonationManagement-0.0.1-SNAPSHOT.jar"]